(* ::Package:: *)

(* ::Input:: *)
(*(* Memory clean*)*)
(*Quit[];*)
(**)
(**)


(* ::Input:: *)
(*ClearAll["Global`*"];*)
(*$HistoryLength=0;*)
(**)
(*(* =====================USER SETTINGS=====================*)*)
(**)
(*state="neel";*)
(*(*state="polarized";*)*)
(**)
(*M=350;*)
(*Jhop=1.0;*)
(*gamma=0.5;*)
(*wp=80;*)
(*kVals=Subdivide[-Pi,Pi,800];*)
(*deltaR={1.1920928955078125*^-7,0.0, 8.457433432340621948*^-3, 0.0, 1.617655251175165176*^-2, 0.0, 1.487755449488759041*^-2, 0.0, 1.141047198325395584*^-2, 0.0,  8.386073750443756580*^-3};*)
(*(*deltaR={1.1920928955078125*^-7,0.0, 8.457433432340621948*^-3, 0.0, 1.617655251175165176*^-2, 0.0, 1.487755449488759041*^-2, 0.0, 1.141047198325395584*^-2};*)*)
(*(*deltaR={1.1920928955078125*^-7,0.0, 8.457433432340621948*^-3, 0.0, 1.617655251175165176*^-2, 0.0, 1.487755449488759041*^-2};*)*)
(*(*deltaR={1.1920928955078125*^-7,0.0, 8.457433432340621948*^-3, 0.0, 1.617655251175165176*^-2};*)*)
(*(*deltaR={1.1920928955078125*^-7,0.0, 8.457433432340621948*^-3};*)*)
(*(*deltaR={1.1920928955078125*^-7};*)*)
(**)
(*deltaTag="delta"<>ToString[Length[deltaR]];*)
(*Print["deltaTag = ",deltaTag];*)
(**)
(**)
(*(* delta Table*)*)
(*deltaRTable={{1.1920928955078125*^-7},{1.1920928955078125*^-7,0.0,8.457433432340621948*^-3},{1.1920928955078125*^-7,0.0,8.457433432340621948*^-3,0.0,1.617655251175165176*^-2},{1.1920928955078125*^-7,0.0,8.457433432340621948*^-3,0.0,1.617655251175165176*^-2,0.0,1.487755449488759041*^-2},{1.1920928955078125*^-7,0.0,8.457433432340621948*^-3,0.0,1.617655251175165176*^-2,0.0,1.487755449488759041*^-2,0.0,1.141047198325395584*^-2},{1.1920928955078125*^-7,0.0,8.457433432340621948*^-3,0.0,1.617655251175165176*^-2,0.0,1.487755449488759041*^-2,0.0,1.141047198325395584*^-2,0.0,8.386073750443756580*^-3}};*)
(**)
(*profileDeltaTable=deltaRTable;*)
(**)
(**)
(*Grid[Prepend[Table[{"delta"<>ToString[Length[d]],Length[d],d},{d,deltaRTable}],{"tag","length","deltaR"}],Frame->All]*)
(**)
(**)
(**)
(*profileList=Join[*)
(*Table[{r,"-"},{r,{1, 3, 5}} ],*)
(*Table[ {r,"+"},{r,{0, 2, 4}}] *)
(*];*)
(**)
(*zetasVal=Join[Subdivide[-2.5,-1.,40],Rest@Subdivide[-1.,1.,160],Rest@Subdivide[1.,2.5,40]];*)
(**)
(**)
(*repoBase="/Users/juan/Desktop/Git/InhomogeneousQuench/C_pp";*)
(*outBase=FileNameJoin[{repoBase,"GHD_NEEL_HYBRID"}];*)
(**)
(*chiCsvDir=FileNameJoin[{outBase,"chi_plus","csv"}];*)
(*chiPngDir=FileNameJoin[{outBase,"chi_plus","png"}];*)
(**)
(*Scan[If[!DirectoryQ[#],CreateDirectory[#,CreateIntermediateDirectories->True]]&,{chiCsvDir,chiPngDir}];*)
(**)
(*Print["chiCsvDir = ",chiCsvDir];*)
(*Print["chiPngDir = ",chiPngDir];*)
(**)
(**)
(*csvDir=FileNameJoin[{outBase,"csv"}];*)
(*pngDir=FileNameJoin[{outBase,"png"}];*)
(**)
(*Scan[If[!DirectoryQ[#],CreateDirectory[#,CreateIntermediateDirectories->True]]&,{csvDir,pngDir}];*)
(**)
(*Print["State =", state];*)
(*Print["csvDir = ",csvDir];*)
(*Print["pngDir = ",pngDir];*)
(**)
(**)
(**)
(**)
(*(*Diagnostic switch*)*)
(*runDiagnostics=True;*)
(*rDiag=3;*)
(*signDiag="-";*)
(*zDiag=-1.4;*)
(*(* =========================================================*)*)
(**)
(**)
(**)
(*finiteRealQ[x_]:=NumericQ[x]&&FreeQ[N[x],_DirectedInfinity|Indeterminate|ComplexInfinity]&&TrueQ[Im[N[x]]==0];*)
(**)
(*ClearAll[SolveTruncatedSystemDirectEff];*)
(*SolveTruncatedSystemDirectEff[M_Integer?Positive,J_?NumericQ,gamma_?NumericQ, delta_List,state_String,wp_:60]:=*)
(*Module[*)
(*{rVals=Range[M],fMat,A,rhs,b, q0, DeltaPad, Awp,rhswp,res,srcIdx},*)
(**)
(*fMat=Table[If[n==r,(32.0 J^2 r^2)/(1-4 r^2),If[EvenQ[n+r],(32.0 J^2 n r)/(n^4-2 n^2 (r^2+1)+(r^2-1)^2),0.0]],{n,1,M},{r,1,M}];*)
(**)
(*(*BC convention:DeltaJ=-2 gamma q0*)*)
(*A=Table[If[r==n,gamma*r*Pi*J,0.0]-fMat[[r,n]],{r,1,M},{n,1,M}];*)
(**)
(*(* q_0 *)*)
(*(*q0 = Table[ (1-(-1)^r)/(2.0 Pi ),{r,1,M}];*)*)
(*q0 =Switch[*)
(*state,*)
(*"neel", Table[ (1-(-1)^r)/(2.0 Pi ),{r,1,M}],*)
(*"polarized", Table[ (1-(-1)^r)/( Pi ),{r,1,M}],*)
(*_, (Print["ERROR: unknown state = ", state]; Return[$Failed])*)
(*];*)
(*(* delta_r *)*)
(*DeltaPad= PadRight[N@delta,M,0.0];*)
(**)
(*(* numerics *)*)
(*rhs= gamma J q0 - DeltaPad;*)
(*Print["Dimensions[A] = ",Dimensions[A],", Length[rhs] = ",Length[rhs],", wp = ",wp];*)
(*Awp=SetPrecision[A,wp];*)
(*rhswp=SetPrecision[rhs,wp];*)
(*b=LinearSolve[Awp,rhswp];*)
(*res=Norm[Awp . b-rhswp]/Max[Norm[rhswp],10^-50];*)
(*Print["relative residual = ",N[res,20]];*)
(*{rVals,N[b,30]}];*)
(**)
(*ClearAll[stepTheta,nBase,nL,nR,ChiPlus,nZeta,qPlus,qMinus];*)
(*stepTheta[x_?NumericQ]:=Which[x>0,1.,x<0,0.,True,0.5];*)
(**)
(*nBase[k_?NumericQ,r_Integer?NonNegative,J_?NumericQ,mode_String]:=*)
(*Switch[mode,"-", -2.0J  Sin[ r k],"+",2.0J Cos[r k] ];*)
(**)
(*nL[k_?NumericQ]:=0 ;*)
(*(*nR[k_?NumericQ]:= 1/(4  Pi);*)*)
(*nR[k_?NumericQ]:=Switch[*)
(*state,*)
(*"neel",1/(4 Pi),*)
(*"polarized",1/(2 Pi),*)
(*_,Indeterminate*)
(*];*)
(**)
(**)
(*ChiPlus[k_?NumericQ,rVals_List,bVals_List]:=stepTheta[k] (nL[k]+bVals . Sin[rVals k])+stepTheta[-k] (nR[k]+bVals . Sin[rVals k]);*)
(**)
(*nZeta[k_?NumericQ,zeta_?NumericQ,rVals_List,bVals_List]:=*)
(*Module[{epsp=2. Sin[k],chi},chi=ChiPlus[k,rVals,bVals];*)
(*If[k>0,stepTheta[-zeta] nL[k]+stepTheta[zeta] stepTheta[epsp-zeta] chi+stepTheta[zeta-epsp] nR[k],stepTheta[zeta] nR[k]+stepTheta[-zeta] stepTheta[-epsp+zeta] chi+stepTheta[epsp-zeta] nL[k]]];*)
(**)
(**)
(*ClearAll[chargeIntegrand,currentIntegrand];*)
(*chargeIntegrand[k_?NumericQ,r_Integer?NonNegative, J_?NumericQ,zeta_?NumericQ,sign_String,rVals_List,bVals_List]:=*)
(*If[sign==="-",nBase[k,r, J, "-"],nBase[k,r, J, "+"]]*nZeta[k,zeta,rVals,bVals];*)
(**)
(*currentIntegrand[k_?NumericQ,r_Integer?NonNegative,J_?NumericQ,zeta_?NumericQ,sign_String,rVals_List,bVals_List]:=*)
(*2.0 Sin[k]*If[sign==="-",nBase[k,r, J, "-"],nBase[k,r, J, "+"]]*nZeta[k,zeta,rVals,bVals];*)
(**)
(*ClearAll[qAt,jAt];*)
(**)
(*qAt[z_?NumericQ,rval_Integer?NonNegative, J_?NumericQ,signval_String,rVals_List,bVals_List]:=Module[{res},res=Check[Quiet[NIntegrate[Evaluate@chargeIntegrand[k,rval,J, z,signval,rVals,bVals],{k,-Pi,Pi},Method->{"GlobalAdaptive","SymbolicProcessing"->0},MinRecursion->3,MaxRecursion->20,WorkingPrecision->25,AccuracyGoal->8,PrecisionGoal->10],{NIntegrate::slwcon,NIntegrate::ncvb,NIntegrate::eincr}],$Failed,{NIntegrate::inumr}];*)
(*If[res===$Failed||!finiteRealQ[res],Indeterminate,N[res,16]]];*)
(**)
(*jAt[z_?NumericQ,rval_Integer?NonNegative, J_?NumericQ,signval_String,rVals_List,bVals_List]:=Module[{res},res=Check[Quiet[NIntegrate[Evaluate@currentIntegrand[k,rval,J, z,signval,rVals,bVals],{k,-Pi,Pi},Method->{"GlobalAdaptive","SymbolicProcessing"->0},MinRecursion->3,MaxRecursion->20,WorkingPrecision->25,AccuracyGoal->8,PrecisionGoal->10],{NIntegrate::slwcon,NIntegrate::ncvb,NIntegrate::eincr}],$Failed,{NIntegrate::inumr}];*)
(*If[res===$Failed||!finiteRealQ[res],Indeterminate,N[res,16]]];*)
(**)
(**)
(**)


(* ::Input:: *)
(*(*----------Solve once----------*)*)
(*sol=SolveTruncatedSystemDirectEff[M,Jhop,gamma,deltaR, state, wp];*)
(*{rVals,bVals}=sol;*)
(*Do[{rval, signval}=rss;*)
(*Print["Running r=",rval," sign=",signval];*)
(*,{rss,profileList}];*)


(* ::Input:: *)
(*(* --- Check if variables are properly declared --- *)*)
(*deltaR//InputForm*)
(*FreeQ[deltaR,e]*)
(*NumericQ/@deltaR*)


(* ::Input:: *)
(*(* Run ChiPlus for all deltas in deltaRTable*)*)


(* ::Input:: *)
(*Do[*)
(*Module[*)
(*{deltaTagLocal,solLocal,rValsLocal,bValsLocal,chiVals,badChi,*)
(*dataVals,plot,gammaTagLocal,stateTagLocal,fileST,csvOut,pngOut},*)
(**)
(*deltaTagLocal="delta"<>ToString[Length[delta]];*)
(**)
(*Print["Running ChiPlus for state=",state," ",deltaTagLocal];*)
(**)
(*solLocal=SolveTruncatedSystemDirectEff[M,Jhop,gamma,delta,state,wp];*)
(*If[solLocal===$Failed,*)
(*Print["ERROR: solver failed for ",deltaTagLocal];*)
(*Continue[];];*)
(**)
(*{rValsLocal,bValsLocal}=solLocal;*)
(**)
(*chiVals=N[ChiPlus[#,rValsLocal,bValsLocal]&/@kVals,16];*)
(**)
(*badChi=Flatten@Position[chiVals,_?(Not@*finiteRealQ),{1},Heads->False];*)
(**)
(*If[badChi=!={},Print["ERROR: non-numeric ChiPlus values found. badChi=",badChi];*)
(*Continue[];*)
(*];*)
(**)
(*dataVals=N@Transpose[{kVals,chiVals}];*)
(**)
(*plot=ListLinePlot[*)
(*{Transpose[{kVals,chiVals}]},*)
(*PlotLegends->{"ChiPlus"},*)
(*Frame->True,*)
(*FrameLabel->{"k","\[Chi]Plus"},*)
(*PlotLabel->Row[{*)
(*ToUpperCase[state]," ChiPlus, ",deltaTagLocal,*)
(*", M=",M,*)
(*", gamma=",gamma,*)
(*", wp=",wp*)
(*}],*)
(*ImageSize->700*)
(*];*)
(**)
(*gammaTagLocal=StringReplace[*)
(*ToString@NumberForm[N[gamma],{Infinity,2},NumberPadding->{"","0"}],*)
(*" "->""];*)
(**)
(*stateTagLocal=Switch[*)
(*state,*)
(*"neel","NEEL",*)
(*"polarized","POLARIZED",*)
(*_,"UNKNOWN"*)
(*];*)
(**)
(*fileST=StringTemplate[*)
(*"CHI_PLUS_``_``_M``_gamma``_wp``"*)
(*][stateTagLocal,deltaTagLocal,M,gammaTagLocal,wp];*)
(**)
(*csvOut=FileNameJoin[{chiCsvDir,fileST<>".csv"}];*)
(*pngOut=FileNameJoin[{chiPngDir,fileST<>".png"}];*)
(**)
(*Export[csvOut,Prepend[dataVals,{"k","ChiPlus"}],"CSV"];*)
(*Export[pngOut,plot,"PNG"];*)
(**)
(*Print["Saved ChiPlus CSV: ",csvOut];*)
(*Print["Saved ChiPlus PNG: ",pngOut];*)
(*],*)
(*{delta,deltaRTable}*)
(*];*)
(**)
(**)
(*(*----------Optional diagnostics----------*)*)
(*Print["=== BEGIN DIAGNOSTICS ==="];*)
(*z0=-0.0033333;*)
(*q0=qAt[z0,rDiag,Jhop,signDiag,rVals,bVals];*)
(*j0=jAt[z0,rDiag, Jhop, signDiag,rVals,bVals];*)
(*{rDiag*q0,finiteRealQ[q0]}*)
(*{q0,finiteRealQ[q0]}*)
(*{j0,finiteRealQ[j0]}*)
(*Print["=== END DIAGNOSTICS ==="];*)
(**)
(**)


(* ::Input:: *)
(*(* Smoke gun for badly rendered names *)*)
(**)
(*{rval,signval}=First[profileList];*)
(**)
(*stateTag=Switch[state,"neel","NEEL","polarized","POLARIZED",_,"UNKNOWN"];*)
(**)
(*gammaTag=StringReplace[ToString@NumberForm[N[gamma],{Infinity,2},NumberPadding->{"","0"}]," "->""];*)
(**)
(**)
(*StringTemplate["GHD_``_HYBRID_``_r``_sign``_M``_gamma``_wp``_seggrid"][stateTag,deltaTag,rval,signval,M,gammaTag,wp]*)
(**)
(**)
(**)


(* ::Input:: *)
(*(*----------Full profiles+export----------*)*)
(**)
(*Do[*)
(*Module[*)
(*{deltaTagLocal,solLocal,rValsLocal,bValsLocal,gammaTagLocal,stateTagLocal},*)
(**)
(*deltaTagLocal="delta"<>ToString[Length[delta]];*)
(*Print["=== Running profiles for ",state," ",deltaTagLocal," ==="];*)
(**)
(*solLocal=SolveTruncatedSystemDirectEff[M,Jhop,gamma,delta,state,wp];*)
(*If[solLocal===$Failed,*)
(*Print["ERROR: solver failed for ",deltaTagLocal];*)
(*Continue[];*)
(*];*)
(**)
(*{rValsLocal,bValsLocal}=solLocal;*)
(**)
(*gammaTagLocal=StringReplace[*)
(*ToString@NumberForm[N[gamma],{Infinity,2},NumberPadding->{"","0"}],*)
(*" "->""*)
(*];*)
(**)
(*stateTagLocal=Switch[*)
(*state,*)
(*"neel","NEEL",*)
(*"polarized","POLARIZED",*)
(*_,"UNKNOWN"*)
(*];*)
(**)
(*Do[*)
(*Module[*)
(*{qVals,JVals,badQ,badJ,dataVals,plot,fileST,csvOut,pngOut,rval,signval},*)
(**)
(*{rval,signval}=rs;*)
(*Print["Running ",deltaTagLocal," r=",rval," sign=",signval];*)
(**)
(*qVals=qAt[#,rval,Jhop,signval,rValsLocal,bValsLocal]&/@zetasVal;*)
(*JVals=jAt[#,rval,Jhop,signval,rValsLocal,bValsLocal]&/@zetasVal;*)
(**)
(*badQ=Flatten@Position[qVals,_?(Not@*finiteRealQ),{1},Heads->False];*)
(*badJ=Flatten@Position[JVals,_?(Not@*finiteRealQ),{1},Heads->False];*)
(**)
(*If[badQ=!={}||badJ=!={},*)
(*Print["ERROR: non-numeric values found. badQ=",badQ," badJ=",badJ];*)
(*Continue[];*)
(*];*)
(**)
(*dataVals=N@Transpose[{zetasVal,qVals,JVals}];*)
(**)
(*plot=ListLinePlot[*)
(*{*)
(*Transpose[{zetasVal,qVals}],*)
(*Transpose[{zetasVal,JVals}]*)
(*},*)
(*PlotLegends->{"q","J"},*)
(*Frame->True,*)
(*FrameLabel->{"zeta","value"},*)
(*PlotLabel->Row[{*)
(*ToUpperCase[state]," hybrid, ",deltaTagLocal,*)
(*", r=",rval,*)
(*", sign=",signval,*)
(*", M=",M,*)
(*", gamma=",gamma,*)
(*", wp=",wp*)
(*}],*)
(*ImageSize->700*)
(*];*)
(**)
(*fileST=StringTemplate[*)
(*"GHD_``_HYBRID_``_r``_sign``_M``_gamma``_wp``_seggrid"*)
(*][stateTagLocal,deltaTagLocal,rval,signval,M,gammaTagLocal,wp];*)
(**)
(*csvOut=FileNameJoin[{csvDir,fileST<>".csv"}];*)
(*pngOut=FileNameJoin[{pngDir,fileST<>".png"}];*)
(**)
(*Export[csvOut,Prepend[dataVals,{"zeta","q","J"}],"CSV"];*)
(*Export[pngOut,plot,"PNG"];*)
(**)
(*Print["Saved CSV: ",csvOut];*)
(*Print["Saved PNG: ",pngOut];*)
(*],*)
(*{rs,profileList}*)
(*];*)
(*],*)
(*{delta,profileDeltaTable}*)
(*];*)
(**)
